### ISSUE TITLE
Create User database

### ISSUE THREAD

**Issue by cml2377** [bwmccray/Co-Lab#1]
Login with Github
Model should have 

-name
-profile pic
-email
-their profile description
-skills -> empty array for them to edit their strength and weaknesses.

-User should be able to edit their skills, and have two buttons to create team and to find teams

-When user clicks join team , display team on the user dashboard with table and have new button to 'leave team' <- self delete themselves by ID' and regenerate their empty dashboard. Also, want to be able to notify team leader via email that someone joined their team

**Comment by livingkurt** [comment]
User Database is created
