### ISSUE TITLE
Create Team database

### ISSUE THREAD

**Issue by cml2377** [bwmccray/Co-Lab#2]
Creating db that holds info on the team. 
-needs to include:

- Team Name
- number of members
- team description
- brief project description 
- holding added members
- status : open or closed registration

-if team is closed, then don't display on rotation

- Display the teams
- Be able to delete members

-When you create team, gives you the form to fill out the DB fields. Then click, "Submit", and it will go back to user dashboard with a table showing current members. Team Lead should be able to delete users and to deactivate project

**Comment by bwmccray** [comment]
test
